name: CI

on:
  push:
    branches: [ main ]

jobs:
  CI-Build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Test
        run: mvn clean test 

      - name: Build
        run: mvn clean install -DskipITs=true -DskipTests=true 

      - name: Install GraalVM and Native Image
        run: |
          wget https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.3.0/graalvm-ce-java17-linux-amd64-22.3.0.tar.gz
          tar -xvzf graalvm-ce-java17-linux-amd64-22.3.0.tar.gz
          sudo mv graalvm-ce-java17-22.3.0 /opt/graalvm
          export PATH=/opt/graalvm/bin:$PATH
          /opt/graalvm/bin/gu install native-image

      - name: Verify GraalVM Installation
        run: |
          # Verify GraalVM and native-image installation
          java -version
          native-image --version

      - name: Build native image
        run: |
          native-image -jar helloworld-1.0.0.jar

      - name: Build image
        id: build-image
        run: docker build .